program SwimClubMeet2;

uses
  Vcl.Forms,
  Vcl.Themes,
  Vcl.Styles,
  XSuperJSON in 'JSON\XSuperJSON.pas',
  XSuperObject in 'JSON\XSuperObject.pas',
  uUtility in 'TOOLS\uUtility.pas',
  dmCORE in 'DATA\dmCORE.pas' {CORE: TDataModule},
  dmIMG in 'DATA\dmIMG.pas' {IMG: TDataModule},
  dmMM_CORE in 'MEMBERS\dmMM_CORE.pas' {MM_CORE: TDataModule},
  dmMM_House in 'MEMBERS\dmMM_House.pas' {MM_House: TDataModule},
  uDefines in 'DATA\uDefines.pas',
  uSettings in 'DATA\uSettings.pas',
  uSwimClub in 'DATA_Helper\uSwimClub.pas',
  uSession in 'DATA_Helper\uSession.pas',
  uEvent in 'DATA_Helper\uEvent.pas',
  uNominee in 'DATA_Helper\uNominee.pas',
  uIntercepters in 'TOOLS\uIntercepters.pas',
  uHeat in 'DATA_Helper\uHeat.pas',
  uLane in 'DATA_Helper\uLane.pas',
  frFrameSession in 'FRAMES\frFrameSession.pas' {FrameSession: TFrame},
  frFrameEvent in 'FRAMES\frFrameEvent.pas' {FrameEvent: TFrame},
  frFrameNominate in 'FRAMES\frFrameNominate.pas' {FrameNominate: TFrame},
  frFrameFilterMember in 'FRAMES\frFrameFilterMember.pas' {FrameFilterMember: TFrame},
  frFrameHeat in 'FRAMES\frFrameHeat.pas' {FrameHeat: TFrame},
  frFrameLane in 'FRAMES\frFrameLane.pas' {FrameLane: TFrame},
  frFrameNavEv in 'FRAMES\frFrameNavEv.pas' {FrameNavEv: TFrame},
  frFrameNavEvItem in 'FRAMES\frFrameNavEvItem.pas' {FrameNavEvItem: TFrame},
  frmMain2 in 'frmMain2.pas' {Main2},
  dlgMemberPicker in 'PICKERS\dlgMemberPicker.pas' {MemberPicker},
  dlgscmDatePicker in 'PICKERS\dlgscmDatePicker.pas' {scmDatePicker},
  frFrameClubGroup in 'SWIMCLUBS\SC_FRAMES\frFrameClubGroup.pas' {FrameClubGroup: TFrame},
  dlgSwimClub_Manage in 'SWIMCLUBS\SC_DIALOGS\dlgSwimClub_Manage.pas' {SwimClubManage},
  dlgSwimClub_Switch in 'SWIMCLUBS\SC_DIALOGS\dlgSwimClub_Switch.pas' {SwimClubSwitch},
  dlgSwimClubGroup_View in 'SWIMCLUBS\SC_DIALOGS\dlgSwimClubGroup_View.pas' {SwimClubGroup_View},
  dlgSwimClubPicker in 'SWIMCLUBS\SC_PICKERS\dlgSwimClubPicker.pas' {SwimClubPicker},
  rptClub_MembersDetail in 'SWIMCLUBS\SC_REPORTS\rptClub_MembersDetail.pas' {Club_MembersDetail: TDataModule},
  rptClub_MembersList in 'SWIMCLUBS\SC_REPORTS\rptClub_MembersList.pas' {Club_MembersList: TDataModule},
  rptClub_MembersSummary in 'SWIMCLUBS\SC_REPORTS\rptClub_MembersSummary.pas' {Club_MembersSummary: TDataModule},
  SCMSimpleConnect in 'TOOLS\SCMSimpleConnect.pas',
  frmDisqualificationCodes in 'TOOLS\frmDisqualificationCodes.pas' {DisqualificationCodes},
  dlgLogin in 'TOOLS\T_DIALOGS\dlgLogin.pas' {Login},
  dlgPoolTypes in 'TOOLS\T_DIALOGS\dlgPoolTypes.pas' {PoolTypes},
  dlgPreferences in 'TOOLS\T_DIALOGS\dlgPreferences.pas' {Preferences},
  dlgQualifyTimes in 'TOOLS\T_DIALOGS\dlgQualifyTimes.pas' {QualifyTimes},
  rptQTDistStrokeReportA in 'TOOLS\T_REPORTS\rptQTDistStrokeReportA.pas' {QTDistStrokeReportA: TDataModule},
  rptQTMemberReportA in 'TOOLS\T_REPORTS\rptQTMemberReportA.pas' {QTMemberReportA: TDataModule},
  rptQTNotQualified in 'TOOLS\T_REPORTS\rptQTNotQualified.pas' {QTNotQualified: TDataModule},
  rptQTSessionReportA in 'TOOLS\T_REPORTS\rptQTSessionReportA.pas' {QTSessionReportA: TDataModule},
  rptQTTableReportA in 'TOOLS\T_REPORTS\rptQTTableReportA.pas' {QTTableReportA: TDataModule},
  frFrameMM_ListMember in 'MEMBERS\MM_FRAMES\frFrameMM_ListMember.pas' {FrameMM_ListMember: TFrame},
  frFrameMM_SwimClub in 'MEMBERS\MM_FRAMES\frFrameMM_SwimClub.pas' {frameMM_SwimClub: TFrame},
  frFrameMM_ContactNum in 'MEMBERS\MM_FRAMES\frFrameMM_ContactNum.pas' {FrameMM_ContactNum: TFrame},
  frmMM_Stats in 'MEMBERS\frmMM_Stats.pas' {ManageMember_Stats},
  frmMM_CheckData in 'MEMBERS\frmMM_CheckData.pas' {ManageMember_CheckData},
  frmManageMember in 'MEMBERS\frmManageMember.pas' {ManageMember},
  frmMM_ParaOlympic in 'MEMBERS\frmMM_ParaOlympic.pas' {MM_ParaOlympic},
  frmMM_Roles in 'MEMBERS\frmMM_Roles.pas' {MM_Roles},
  frmMM_MetaData in 'MEMBERS\frmMM_MetaData.pas' {MM_MetaData},
  dlgMM_About in 'MEMBERS\MM_DIALOGS\dlgMM_About.pas' {MM_About},
  dlgMM_Delete in 'MEMBERS\MM_DIALOGS\dlgMM_Delete.pas' {MM_Delete},
  dlgMM_FilterByParam in 'MEMBERS\MM_DIALOGS\dlgMM_FilterByParam.pas' {MM_FilterByParam},
  dlgMM_FilterBySwimClub in 'MEMBERS\MM_DIALOGS\dlgMM_FilterBySwimClub.pas' {MM_FilterBySwimClub},
  dlgMM_Find in 'MEMBERS\MM_DIALOGS\dlgMM_Find.pas' {MM_Find},
  dlgMM_Find_FName in 'MEMBERS\MM_DIALOGS\dlgMM_Find_FName.pas' {FindMember_FName},
  dlgMM_Find_ID in 'MEMBERS\MM_DIALOGS\dlgMM_Find_ID.pas' {FindMember_ID},
  dlgMM_Find_Membership in 'MEMBERS\MM_DIALOGS\dlgMM_Find_Membership.pas' {FindMember_Membership},
  rptMM_Chart in 'MEMBERS\MM_REPORTS\rptMM_Chart.pas' {MemberChart: TDataModule},
  rptMM_CheckData in 'MEMBERS\MM_REPORTS\rptMM_CheckData.pas' {MemberCheckData: TDataModule},
  rptMM_Detail in 'MEMBERS\MM_REPORTS\rptMM_Detail.pas' {MemberDetail: TDataModule},
  rptMM_History in 'MEMBERS\MM_REPORTS\rptMM_History.pas' {MemberHistory: TDataModule},
  frmSwimClubType in 'SWIMCLUBS\frmSwimClubType.pas' {SwimClubType},
  frmSwimClub_Reports in 'SWIMCLUBS\SC_REPORTS\frmSwimClub_Reports.pas' {SwimClub_Reports},
  uStateString in 'DATA_Helper\uStateString.pas',
  dlgEntrantPicker in 'LANES\dlgEntrantPicker.pas' {EntrantPicker},
  dlgEntrantPickerCTRL in 'LANES\dlgEntrantPickerCTRL.pas' {EntrantPickerCTRL},
  dlgLaneColumnPicker in 'LANES\dlgLaneColumnPicker.pas' {LaneColumnPicker},
  dlgTeamPicker in 'LANES\dlgTeamPicker.pas' {TeamPicker},
  dlgTeamPickerCTRL in 'LANES\dlgTeamPickerCTRL.pas' {TeamPickerCTRL},
  uPickerStage in 'LANES\uPickerStage.pas',
  dlgEditSession in 'SESSIONS\dlgEditSession.pas' {EditSession},
  dlgNewSession in 'SESSIONS\dlgNewSession.pas' {NewSession},
  dmSCM2 in 'DATA\dmSCM2.pas' {SCM2: TDataModule},
  dlgAutoBuild_Heats in 'AUTOBUILD\INDV\dlgAutoBuild_Heats.pas' {AutoBuild_Heats},
  dmAutoBuild_INDVHeats in 'AUTOBUILD\INDV\dmAutoBuild_INDVHeats.pas' {AutoBuild_INDVHeats: TDataModule};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  TStyleManager.TrySetStyle('Windows10 SlateGray');
  Application.CreateForm(TSCM2, SCM2);
  Application.CreateForm(TCORE, CORE);
  Application.CreateForm(TIMG, IMG);
  Application.CreateForm(TMain2, Main2);
  Application.Run;

end.
